//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCrud.DbCtx
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MukeshDb : DbContext
    {
        public MukeshDb()
            : base(ModifyConnectionString("MukeshDb"))
        {
        }

        private static string ModifyConnectionString(string databaseName)
        {
            // Original connection string

            var connectionString = ConfigurationManager.ConnectionStrings["MukeshDb"].ConnectionString;
            // Replace the initial catalog with the desired database name
            connectionString = connectionString.Replace("initial catalog=xxxx", $"initial catalog={databaseName}");

            return connectionString;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Friend> Friends { get; set; }
    }
}
